In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
cwd = os.getcwd()
df = pd.read_csv(os.path.join(cwd, "data", "final_data.csv"))
df

,symbol,sector,sub_sector,investing_symbol
0,1A0,Cyclical Consumer Services,Restaurants & Bars,NaN
1,1A1,Industrial Goods,Industrial Machinery & Equipment,NaN
2,1A4,Holding Companies,Investment Holding Companies,NaN
3,1AZ,Cyclical Consumer Services,Consumer Publishing,NaN
4,1B0,Cyclical Consumer Services,Entertainment Production,NaN
...,...,...,...,...
589,ZXY,Industrial & Commercial Services,Construction & Engineering,NaN
590,NaN,Energy,Oil & Gas,TPED
591,NaN,Industrials,Transport Infrastructure,TATD
592,NaN,Consumer Non-Cyclicals,Food & Drug Retailing,TCPD
593,NaN,Healthcare,Healthcare Providers & Services,9G2